// src/templates/HomeTemplate/Contact.tsx
import { Heading2 } from "@/components/Heading2";
import { Form } from "@/features/contact/components/Form";

export const Contact = () => {
  return (
    <section id="contact" className="px-4">
      <div className="space-y-4 sm:space-y-12">
        <Heading2>Contact</Heading2>
        <Form />
      </div>
    </section>
  );
};

// src/routes/contact/+page.svelte
<script lang="ts">
  import { Heading1 } from "$lib/components";
  import { ContactForm } from "$lib/features/contact-form";
  import type { FormResponse } from "$lib/features/contact-form";

  export let form: FormResponse | null;
  export let data;
</script>

<main class="mx-auto max-w-2xl space-y-10 py-12">
  <Heading1>contact</Heading1>
  <ContactForm {form} formData={data.formData} />
</main>
