// src/components/templates/Home/About/index.tsx
import Image from "next/image";
import { Heading2 } from "@/components/atoms/Heading2";
import { Heading3 } from "@/components/atoms/Heading3";
import { skills } from "@/constants/skills";
import { Skills } from "./Skills";

export const About = () => {
  return (
    <section id="about">
      <Heading2>About Me</Heading2>
      <div className="grid pt-8 sm:grid-cols-2">
        <Image
          src="/img/profile.webp"
          alt="profile"
          width={144}
          height={144}
          className="mx-auto my-8"
        />
        <div className="space-y-4">
          <p>
            I&apos;m Kanaru Sasaki. My current job is web application
            development, and my recent hobby is web application development.
          </p>
          <div>
            <div className="py-2">
              <Heading3>skills i work with recently</Heading3>
            </div>
            <Skills skills={skills.recent} />
            <details>
              <summary className="w-32 cursor-pointer py-2 text-gray-400">
                <Heading3>other skills</Heading3>
              </summary>
              <Skills skills={skills.other} />
            </details>
          </div>
        </div>
      </div>
    </section>
  );
};

// src/routes/(pages)/about/+page.svelte
<script lang="ts">
  import { Meta } from "$lib/components";
</script>

<Meta
  title="About | Kanaru"
  description="佐々木哉瑠(かなる)のポートフォリオサイト"
/>

<h1>about</h1>
<div class="space-y-12">
  <section class="grid grid-cols-2 gap-4 md:gap-8">
    <img src="/profile.png" alt="profile" class="ml-auto w-full max-w-48" />
    <div>
      <h2>Sasaki Kanaru</h2>
      <p class="text-xs">佐々木 哉瑠</p>
      <div class="mt-3 text-sm">
        <p>2000年生まれ。</p>
        <p>仙台で活動するwebエンジニアです。</p>
      </div>
    </div>
  </section>

  <section>
    <h2>Skills</h2>
    <div class="mt-3 text-sm">
      <p>
        React.js, Next.js,
        TypeScriptをメインにフロントエンドポジションで活動しています。
      </p>
    </div>
  </section>
</div>
